// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtikG5CCKS-fa7ZEOY2dLCzFHiGBClUVU',
    appId: '1:104294309891:web:bfd133d7ce47073454ee36',
    messagingSenderId: '104294309891',
    projectId: 'lab29-10',
    authDomain: 'lab29-10.firebaseapp.com',
    storageBucket: 'lab29-10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR-Y62AN6wsOaXR53DegWZzRPvB9aaQws',
    appId: '1:104294309891:android:f9ceb372798bfd4854ee36',
    messagingSenderId: '104294309891',
    projectId: 'lab29-10',
    storageBucket: 'lab29-10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK3mtD5Wk6pdScqLgLeHOZlXU0iZFKI0w',
    appId: '1:104294309891:ios:6439182e0ebd0f1754ee36',
    messagingSenderId: '104294309891',
    projectId: 'lab29-10',
    storageBucket: 'lab29-10.appspot.com',
    iosClientId: '104294309891-kp5dmdq6ku514c22peatd95cjfchd6c9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourlab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK3mtD5Wk6pdScqLgLeHOZlXU0iZFKI0w',
    appId: '1:104294309891:ios:6439182e0ebd0f1754ee36',
    messagingSenderId: '104294309891',
    projectId: 'lab29-10',
    storageBucket: 'lab29-10.appspot.com',
    iosClientId: '104294309891-kp5dmdq6ku514c22peatd95cjfchd6c9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourlab',
  );
}
